name: SocialNetworking.Backend - Deploy

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1
      
      - name: Buildando e deployando o projeto para o Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          PROJECT_NAME: "APIRest"
        run: |
          cd SocialNetworking.Backend/${PROJECT_NAME}/
          dotnet publish -c Release -r linux-x64 -p:PublishReadyToRun=true -o ../publish
          cd ../publish
          
          dockerfileContent="FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim\n"
          dockerfileContent+="WORKDIR /app\n"
          dockerfileContent+="COPY . .\n"
          dockerfileContent+="CMD ASPNETCORE_URLS=http://*:$PORT ./${PROJECT_NAME}"
          
          echo -e $dockerfileContent > Dockerfile
          
          docker build -t ${{ secrets.HEROKU_APP_NAME }} .
          
          heroku container:login
          heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}
          heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
          heroku config:set JWT_SIGNINGKEY=${{ secrets.JWT_SIGNINGKEY }} -a ${{ secrets.HEROKU_APP_NAME }}
          
          echo "Deploy concluído com sucesso!"
